version: '2'
networks:
    symfony: 
        driver: 'bridge'

volumes:
    logs:
        driver: 'local'
    database:
        driver: 'local'
    php-socket:
        driver: 'local'

services: 
    symfony:
        image: iulyanpopa/alpine-web
        container_name: data
        volumes:
            - ./www:/var/www
            - logs:/var/www/var/logs
        command: 'true'

        networks:
            - symfony

    php-fpm:
        image: iulyanpopa/alpine-php-fpm
        container_name: php-fpm
        volumes_from:
            - symfony
        volumes:
            - logs:/var/log/php-fpm
            - php-socket:/var/run/symfony
        depends_on:
            - mysql
        networks:
            - symfony

    nginx:
        image: iulyanpopa/alpine-nginx
        container_name: nginx
        volumes_from:
            - symfony
        ports:
            - 80:80
        volumes:
            - logs:/var/log/nginx
            - php-socket:/var/run/symfony
        depends_on:
            - php-fpm
        networks:
            - symfony

    mysql:
        image: mysql/mysql-server
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_DATABASE: symfony
            MYSQL_PASSWORD: secret
        networks:
            - symfony