version: '2'
networks:
    symfony: 
        driver: 'bridge'

volumes:
    logs:
        driver: 'local'
    database:
        driver: 'local'
    php-socket:
        driver: 'local'

services:
##
## Uncomment this service if you want to use gulp
## A new container for gulp will start and by default
## will run `gulp` and then exit.
## To run gulp later just use
## `docker start -i gulp`
##
#    gulp:
#        image: iulyanpopa/alpine-gulp
##        build:
##            context: ./gulp
##            dockerfile: ./Dockerfile
#        container_name: gulp
#        volumes_from:
#            - symfony
#        command: 'gulp'
#        networks:
#            - symfony

    symfony:
        image: iulyanpopa/alpine-web
#        build:
#            context: ./alpine-web
#            dockerfile: ./Dockerfile
        container_name: data
        volumes:
            - ./www/:/var/www
            - logs:/var/www/var/logs
        command: 'true'
        networks:
            - symfony

    rabbit:
        image: rabbitmq:3-management
        container_name: sf-rabbitmq
        ports:
            - 8081:15672
            - 5672:5672
            - 5671:5671
        environment:
            RABBITMQ_DEFAULT_PASS: pass
            RABBITMQ_DEFAULT_USER: user
#            RABBITMQ_DEFAULT_VHOST: vhost
        networks:
            - symfony

    redis:
        container_name: sf-redis
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - symfony

    mysql:
        image: mysql/mysql-server
        container_name: sf-mysql
        ports:
            - 3306:3306
        volumes:
            - database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_DATABASE: symfony
            MYSQL_PASSWORD: secret
        networks:
            - symfony

    php-fpm:
        image: iulyanpopa/alpine-php-fpm7
#        build:
#            context: ./php-fpm
#            dockerfile: ./Dockerfile
        container_name: sf-php-fpm
        volumes_from:
            - symfony
        volumes:
            - logs:/var/log/php-fpm
            - php-socket:/var/run/symfony
        depends_on:
            - mysql
        environment:
            - MY_UID=${MY_UID}
            - MY_GID=${MY_GID}
        networks:
            - symfony

    nginx:
        image: iulyanpopa/alpine-nginx
#        build:
#            context: ./nginx
#            dockerfile: ./Dockerfile
        container_name: sf-nginx
        volumes_from:
            - symfony
        ports:
            - 80:80
        volumes:
            - logs:/var/log/nginx
            - php-socket:/var/run/symfony
        depends_on:
            - php-fpm
        environment:
            - MY_UID=${MY_UID}
            - MY_GID=${MY_GID}
        networks:
            - symfony

    elk:
        image: willdurand/elk
        container_name: sf-elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - symfony
            - php-fpm
            - nginx
